name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          choco upgrade -y openssl.light
          choco install -y visualstudio2022community
          choco install -y visualstudio2022buildtools --package-parameters "--includeRecommended --add Microsoft.VisualStudio.Component.VC.CoreBuildTools"
          choco install -y windows-sdk-11-version-22h2-all
          choco install -y zip git python3 ninja
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"
          $env:WINDOWSSDKDIR="C:\Program Files (x86)\Windows Kits\11\"
          pip3 install wheel reflutter
          pip3 install .
          cd c:/
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          git clone https://github.com/flutter/engine.git
          git clone https://github.com/O2C14/build_dart-lang_sdk.git
          Expand-Archive -Path "C:\build_dart-lang_sdk\DIA SDK.zip" -DestinationPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\DIA SDK\" -Force
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Force
      - name: Sync engine code and dependencies
        run: |
          cd c:\
          $ROOT_DIR = (Get-Location).Path
          $env:PATH = "$env:PATH;$ROOT_DIR\depot_tools"
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"
          $env:WINDOWSSDKDIR="C:\Program Files (x86)\Windows Kits\11\"
          cd engine
          git checkout 3.7.8
          git reset --hard FETCH_HEAD
          cd $ROOT_DIR
          mkdir customEngine
          cd customEngine
          echo 'solutions = [{"managed": False,"name": "src\\flutter","url": "C:\\engine","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' | Out-File -FilePath .gclient -NoNewline -Encoding ASCII
          gclient sync
      - name: Build engine
        run: |
          cd c:\
          $ROOT_DIR = (Get-Location).Path
          $env:PATH = "$env:PATH;$ROOT_DIR\depot_tools"
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"
          $env:WINDOWSSDKDIR="C:\Program Files (x86)\Windows Kits\11\"
          cd c:\customEngine\src\flutter
          python .\tools\gn --no-goma --no-prebuilt-dart-sdk --windows --runtime-mode=release
          ninja -C c:\customEngine\src\out\win_release_x64
      - name: Package engine as zip file
        run: |
          cd c:\customEngine\src\out\
          Compress-Archive -Path win_release_x64 -DestinationPath engine.zip
      - name: Upload engine zip file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: engine
          path: c:/customEngine/src/out/engine.zip
