name: Build dart

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          choco upgrade -y openssl.light
          choco install  -y visualstudio2019community
          choco install visualstudio2019buildtools --package-parameters "--includeRecommended --add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041"
          choco install -y python2.7 zip git python3 ninja
          pip3 install .
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -Force
      - name: Sync engine code and dependencies
        run: |
          $ROOT_DIR = (Get-Location).Path
          $env:PATH = "$env:PATH;$ROOT_DIR\depot_tools"
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"
          $env:WINDOWSSDKDIR="C:\Program Files (x86)\Windows Kits\10\"
          echo 'solutions=[{"name":"sdk","url":"https://dart.googlesource.com/sdk.git@2.19.5","deps_file":"DEPS","managed":False,"custom_deps":{},},]' | Out-File -FilePath .gclient -NoNewline -Encoding ASCII
          gclient sync
      - name: Build engine
        run: |
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:GYP_MSVS_OVERRIDE_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community"
          $env:WINDOWSSDKDIR="C:\Program Files (x86)\Windows Kits\10\"
          .\sdk\tools\build.py --no-goma --mode release --arch x64 create_sdk
      - name: Package sdk as zip file
        run: |
          cd .\sdk\out
          Compress-Archive -Path win_release_x64 -DestinationPath sdk.zip
      - name: Upload engine zip file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: $ROOT_DIR\sdk\out\sdk.zip
